In [2]:
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a)

print(np.arange(20))


[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
L=range(1000)
%timeit [i**2 for i in L]

467 µs ± 41.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a = np.arange(1000)      #numpy array  [0,1,3,...999]
%timeit a**2

1.76 µs ± 107 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
#1-D

a = np.array([0,1,2,3])
print(a)
a.ndim


[0 1 2 3]


1

In [11]:
#2-D, 3-D .......

b = np.array([[0,1,2],[4,6,2]])
b

array([[0, 1, 2],
       [4, 6, 2]])

In [12]:
b.shape

(2, 3)

In [13]:
b.ndim

2

In [14]:
len(b) #returns the size of the first dimension

2

In [16]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
#1-D array is called Vector
#2-D array is called Matrix
#N-D array is called Tensor
c.ndim

3

In [18]:
c.shape

(2, 2, 2)

In [19]:
b = np.arange(1,10,2)  #start,end,number of points
b

array([1, 3, 5, 7, 9])

In [20]:
#using linear space
a = np.linspace(0,1,6) #start,end number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
#common arrays
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a.ndim

2

In [23]:
np.eye(3)  #return a 2-D array with ones on the diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [25]:
#create array using diag function

a = np.diag([1,2,3,4])  #construct a diagonal array.
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
np.diag(a)  #extract diagonal

array([1, 2, 3, 4])

In [27]:
#create array using random

#create an array of the given shape and populate it with random samples from a

a = np.random.rand(4)
a

array([0.07060102, 0.7301472 , 0.53610715, 0.12069073])

In [28]:
a = np.random.randn(4) #return a sample (or samples) from the "standard normal variate
a

array([-0.39796441,  1.44246689, -0.46755705, -2.44282578])

In [29]:
a = np.arange(10)
a.dtype

dtype('int32')

In [32]:
b=np.arange(10,dtype='float64')
print(b)
b.dtype

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


dtype('float64')

In [33]:
d = np.array([1+2j, 2+4j]) #complex datatype
print(d.dtype)

complex128


In [34]:
b = np.array([True,False,True,False])
print(b.dtype)

bool


In [35]:
s = np.array(['Ram','Robert','Rahim'])
s.dtype

dtype('<U6')