In [3]:
import numpy as np
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [4]:
year,hare,lynx,carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [7]:
#The mean populations over time

populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [6]:
#sample standard  Deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [8]:
#which species has the highest population each year?

np.argmax(populations, axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [10]:
#broadcasting

a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print("transpose of A below")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
transpose of A below
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [13]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [14]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [19]:
#another example

a = np.arange(0,40,10)
print(a.shape)
print(a)

(4,)
[ 0 10 20 30]


In [20]:
a = a[:,np.newaxis]  #adds a new axis --> 2D array
print(a.shape)
print(a)

(4, 1)
[[ 0]
 [10]
 [20]
 [30]]


In [21]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [22]:
#Array manipulations
#Flatening
a = np.array([[1,2,3],[4,5,6]])
a.ravel()  #Return a contiguous flattened array. A 1-D array, Containing the 

array([1, 2, 3, 4, 5, 6])

In [23]:
a.T  #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [26]:
#Reshaping
#The invers operation to flattening:

print(a)
print(a.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [27]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [28]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [ ]:
#NOTE AND BEWARE: RESHAPE MAY ALSO RETURN A COPY!:

In [31]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)  
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
#Adding a Dimension

z = np.array([1,2,3])
z

array([1, 2, 3])

In [33]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [34]:
#dimension Shuffling
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [35]:
a.shape

(4, 3, 2)

In [36]:
#to change the value in the 3-D matrix
a[0,2,1]

5

In [46]:
#Resizing

a = np.arange(4)

a.resize((8,))
print(a)

[0 1 2 3 0 0 0 0]


In [47]:
#sorting data

a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [49]:
#in-place sort
print("before",a)
a.sort(axis=1)
a

before [[4 5 6]
 [2 2 3]]


array([[4, 5, 6],
       [2, 2, 3]])

In [51]:
#sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a)   #gets the position of indices of array a
j

array([2, 3, 1, 0], dtype=int64)