In [2]:
import numpy as np
a = np.array([2,4,6,4])
a + 1    #scalar addition

array([3, 5, 7, 5])

In [3]:
a**2

array([ 4, 16, 36, 16], dtype=int32)

In [4]:
b = np.ones(4) + 1
print(b)

[2. 2. 2. 2.]


In [5]:
a - b

array([0., 2., 4., 2.])

In [6]:
a * b

array([ 4.,  8., 12.,  8.])

In [7]:
# Matrix multiplication

c = np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
c*c

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [9]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [10]:
c.ndim

2

In [11]:
c.shape

(4, 4)

In [13]:
a = np.array([1,3,5,2])
b = np.array([1,4,5,3])

a == b

array([ True, False,  True, False])

In [14]:
a>b

array([False, False, False, False])

In [15]:
b>a

array([False,  True, False,  True])

In [16]:
np.array_equal(a,b)

False

In [18]:
#Logical Operations

a = np.array([1,1,0,0], dtype = bool)
b = np.array([1,0,1,0], dtype = bool)
np.logical_and(a,b)

array([ True, False, False, False])

In [19]:
#Transcendental functions:

a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [20]:
np.log(a)

C:\Users\jayakeerthy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [21]:
#Shape Mismatch

a = np.arange(4)
a +np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [22]:
#Basic Reductions
#Computing sums
x = np.array([1,2,3,4])
np.sum(x)

10

In [24]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [25]:
x.sum(axis=0) #column wise sum

array([3, 3])

In [26]:
x.sum(axis=1) #row wise sum

array([2, 4])

In [27]:
#other reductions

x= np.array([1,3,2])
x.min()

1

In [28]:
x.max()

3

In [29]:
x.argmin() #index of minimum element

0

In [30]:
x.argmax() #index of maximum element

1

In [31]:
#Logical Operations
np.all([True, True, False]) #logical AND

False

In [32]:
np.any([True, True, False]) #logical OR

True

In [42]:
#Note: Can be used for array comparisions
a = np.zeros((50, 50))
print(a)
np.any(a != 0)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


False

In [43]:
np.all(a == a)

True

In [44]:
a = np.array([1,2,3,5])
b = np.array([1,8,6,5])
c = np.array([1,2,9,5])
((a<=b) & (b<= c)).all()

False

In [45]:
#Statistics

x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [46]:
np.median(x)

1.5

In [47]:
np.median(y, axis=-1)

array([2., 5.])

In [48]:
x.std()

0.82915619758885