In [2]:
#Indexing and Slicing
import numpy as np
a = np.diag([1,2,3])
print(a[2,2])

3


In [3]:
a[2,1] = 5  #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [4]:
#Slicing
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a[1:8:2]  #Startindex : endindex(exclusive) : step]

array([1, 3, 5, 7])

In [6]:
# we acl also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [7]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning, -1 means reverse order
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [8]:
#copies and views
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [10]:
np.shares_memory(a,b)

True

In [12]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [13]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [14]:
a = np.arange(10)

c = a[::2].copy()   #force a copy
c

array([0, 2, 4, 6, 8])

In [15]:
np.shares_memory(a,c)

False

In [16]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#Fancy Indexing
#Numpy arrays can be indexed with slices, but also with boolen or integer arrays(masks).this method is called fancy Indexing.
#It creates copies not views.

a = np.random.randint(0,20,15)
a


array([10,  3,  7, 19, 11,  5, 18,  0,  0, 15, 14,  1,  7, 19,  8])

In [18]:
mask = (a % 2 == 0)

extract_from_a = a[mask]
extract_from_a

array([10, 18,  0,  0, 14,  8])

In [19]:
#indexing with a mask can be very useful to assign a new value to a sub-array:

a[mask] = -1
a

array([-1,  3,  7, 19, 11,  5, -1, -1, -1, 15, -1,  1,  7, 19, -1])

In [20]:
#Indexing with an array of integers

a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
#indexing can be done with an array of integers,where the same index is reaarnged

a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [23]:
#New values can be assigned

a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [24]:
#load data into numpy array object
data = np.loadtxt('populations.txt')

In [25]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])